### ISSUE TITLE
createJson NullPointerException

### ISSUE THREAD

**Issue by qtdyn** [UnknownDetectionParty/UDP-Java#3]
When I launch MappingGen:

```
Failure to generate mappings: null
java.lang.NullPointerException
	at mapping.MCPJsonGen.createJSON(MCPJsonGen.java:47)
	at mapping.MappingGen.main(MappingGen.java:34)
```

MCPJsonGen:47 is
`File dirSRG = IOUtil.getLatestFile(root, f -> f.getName().equals("notch-srg.srg") && f.getParentFile().getParentFile().getName().equals(mcVersion)).getParentFile();`

Is it just me missing a file?

**Comment by qtdyn** [comment]
I just used `new MCPOnlineJsonGen("1.7.10", false, "stable");`
